spring:
  kafka:
    consumer:
      auto-offset-reset: latest
      group-id: group_id
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317
  application:
    name: my-custom-processor